Assemble same file

diff --git a/.s2i/bin/assemble b/.s2i/bin/assemble
--- a/.s2i/bin/assemble
+++ b/.s2i/bin/assemble
@@ -1,21 +1,132 @@
 #!/bin/sh
-echo "Tar file absolute path: " $APP_LOCATION
 
-echo "Starting Download"
+# Global S2I variable setup
+source `dirname "$0"`/s2i-setup
 
-curl -H "Accept: application/zip" $APP_LOCATION -o ~/${BUNDLE_NAME}
+# Maven arguments setting up the environment
+maven_env_args="-Dmaven.repo.local=${S2I_ARTIFACTS_DIR}/m2"
 
-cd ~
-echo "Bundle Downloaded "
-ls -l | grep "^d"
-#Check If needed
-# Unzip and remove the root directory
+# =========================================================================
+# Helper functions:
 
-echo "Joao: " ${DEPLOYMENTS_DIR}
+function check_error() {
+  local label=$1
+  local error=$2
+  if [ ${error} -ne 0 ]; then
+    echo "Aborting due to error code $error for $label"
+    exit ${error}
+  fi
+}
 
-echo "Unzipping Tar"
-tar -xvzf ${BUNDLE_NAME} -C /deployments/ --strip 1
-echo "Unzip Complete"
-cd ~
-echo "Unzipped Files"
-ls -l | grep "^d"
+function get_output_dir() {
+  local dir=""
+
+  # If multi module build and no ARTIFACT_DIR is set --> error
+  if [ x"${ARTIFACT_DIR}" = x ]; then
+    echo " ${MAVEN_ARGS} ${MAVEN_ARGS_APPEND}" | grep -q ' -pl'
+    if [ $? -eq 0 ]; then
+       echo "ARTIFACT_DIR must be set for multi module Maven builds"
+       exit 1
+    fi
+    dir="${S2I_SOURCE_DIR}/target"
+  else
+    if [ "${ARTIFACT_DIR:0:1}" = "/" ]; then
+       echo "ARTIFACT_DIR \"${ARTIFACT_DIR}\" must not be absolute but relative to the source directory"
+       exit 1
+    fi
+    dir="${S2I_SOURCE_DIR}/${ARTIFACT_DIR}"
+  fi
+
+  # Normalize dir
+  dir=$(echo ${dir} | tr -s /)
+  dir=${dir%/}
+  # The parent must exist but target/ won't exist yet
+  if [ ! -d $(dirname "${dir}"}) ]; then
+    echo "Please specify an existing build directory ARTIFACT_DIR (tried '$(dirname "${dir}")' which does not exist)"
+    exit 1
+  fi
+  echo ${dir}
+}
+
+function copy_dir() {
+  local src=$1
+  local dest=$2
+
+  cp -r ${src}/* ${dest}
+  check_error "copying ${src} to ${dest}" $?
+}
+
+function setup_maven() {
+  if [ -f "${S2I_SOURCE_DIR}/configuration/settings.xml" ]; then
+    maven_env_args="${maven_env_args} -s ${S2I_SOURCE_DIR}/configuration/settings.xml"
+    echo "Using custom maven settings from ${S2I_SOURCE_DIR}/configuration/settings.xml"
+  fi
+}
+
+function build_maven() {
+  # Where artifacts are created during build
+  local build_dir=$1
+
+  # Where to put the artifacts
+  local app_dir=$2
+
+  # Use main class if given
+  local hawtapp_arg=""
+  if [ x"${JAVA_MAIN_CLASS}" != x ]; then
+    hawtapp_arg="-Dhawt-app.javaMainClass=${JAVA_MAIN_CLASS} io.fabric8:hawt-app-maven-plugin:${HAWTAPP_VERSION}:build"
+  fi
+
+  # Default args: no tests, if a module is specified, only build this module
+  local maven_args=${MAVEN_ARGS:-package -DskipTests ${hawtapp_arg} -e}
+
+  echo "Found pom.xml ... "
+  echo "Running 'mvn ${maven_env_args} ${maven_args} ${MAVEN_ARGS_APPEND}'"
+
+  local old_dir=$(pwd)
+  cd ${S2I_SOURCE_DIR}
+  check_error "changing directory to ${S2I_SOURCE_DIR}" $?
+
+  # =========
+  # Run Maven
+  mvn ${maven_env_args} --version
+  mvn ${maven_env_args} ${maven_args} ${MAVEN_ARGS_APPEND}
+  check_error "Maven build" $?
+
+  # ======================
+  # After-build validation
+  if [ ! -d "${build_dir}/hawt-app" ] && [ x"${JAVA_MAIN_CLASS}" = x ]; then
+    echo "No JAVA_MAIN_CLASS specified and no hawt-app-maven-plugin configured in the pom.xml"
+    exit 1
+  fi
+
+  # ==============
+  # Copy artifacts
+  echo "Copying Maven artifacts from ${build_dir}/hawt-app to ${app_dir} ..."
+  copy_dir "${build_dir}/hawt-app" ${app_dir}
+
+  # ======================
+  # Remove repo if desired
+  if [ "x${MAVEN_CLEAR_REPO}" != "x" ]; then
+    rm -rf "${S2I_ARTIFACTS_DIR}/m2"
+    check_error "Cannot remove local Maven repository ${S2I_ARTIFACTS_DIR}/m2" $?
+  fi
+
+  cd ${old_dir}
+}
+
+function get_from_nexus() {
+
+  echo "Starting Download"
+  curl -H "Accept: application/zip" $APP_LOCATION -o ~/${BUNDLE_NAME}
+
+  echo "Unzipping Tar"
+  tar -xvzf ~/${BUNDLE_NAME} -C ${DEPLOYMENTS_DIR} --strip 1
+}
+
+# =========================================================================
+# Main
+
+echo "=================================================================="
+echo "Starting S2I Java Build ....."
+get_from_nexus
+echo "... done"
